### PR TITLE
chore: add test to verify fix of JIRA ticket EXC-1318

### PR DESCRIPTION
**Pull request by crusso**
This test should fail once drun implements raw_rand properly and then be updated to reflect correct operation.

(drun lacks a test suite, so we are abusing Motoko to test the fix once in).

See https://dfinity.atlassian.net/browse/EXC-1318

### CODE REVIEW

**Comment by dragoljub-duric** [comment]
@crusso Thank you!

**Comment by crusso** [comment]
@ggreif I'm seeing non-det behaviour from timer-initial.mo here too, I think.

**Comment by ggreif** [comment]
@crusso I see this on Linux:
```
test-drun-generational-gc> divide-by-zero: [tc] [run] [run-ir] [run-low] [comp] [comp-ref] [valid] [valid-ref] [drun-run]
[3164](https://github.com/dfinity/motoko/actions/runs/4018188380/jobs/6903492980#step:7:3165)
test-drun-generational-gc> --- divide-by-zero.drun-run.ret (expected)
[3165](https://github.com/dfinity/motoko/actions/runs/4018188380/jobs/6903492980#step:7:3166)
test-drun-generational-gc> +++ divide-by-zero.drun-run.ret (actual)
[3166](https://github.com/dfinity/motoko/actions/runs/4018188380/jobs/6903492980#step:7:3167)
test-drun-generational-gc> @@ -0,0 +1 @@
[3167](https://github.com/dfinity/motoko/actions/runs/4018188380/jobs/6903492980#step:7:3168)
test-drun-generational-gc> +Return code 139
[3168](https://github.com/dfinity/motoko/actions/runs/4018188380/jobs/6903492980#step:7:3169)
test-drun-generational-gc> --- divide-by-zero.drun-run (expected)
[3169](https://github.com/dfinity/motoko/actions/runs/4018188380/jobs/6903492980#step:7:3170)
test-drun-generational-gc> +++ divide-by-zero.drun-run (actual)
[3170](https://github.com/dfinity/motoko/actions/runs/4018188380/jobs/6903492980#step:7:3171)
test-drun-generational-gc> @@ -1,2 +1,6 @@
[3171](https://github.com/dfinity/motoko/actions/runs/4018188380/jobs/6903492980#step:7:3172)
test-drun-generational-gc>  ingress Completed: Reply: 0x4449444c016c01b3c4b1f204680100010a00000000000000000101
[3172](https://github.com/dfinity/motoko/actions/runs/4018188380/jobs/6903492980#step:7:3173)
test-drun-generational-gc>  ingress Err: IC0502: Canister rwlgt-iiaaa-aaaaa-aaaaa-cai trapped: integer division by 0
[3173](https://github.com/dfinity/motoko/actions/runs/4018188380/jobs/6903492980#step:7:3174)
test-drun-generational-gc> +/build/test-run-drun-src/run-drun/../drun-wrapper.sh: line 53: 14381 Done                    ( echo "create"; echo "install $ID $1 0x"; if [ -n "$2" ]; then
[3174](https://github.com/dfinity/motoko/actions/runs/4018188380/jobs/6903492980#step:7:3175)
test-drun-generational-gc> +    LANG=C perl -ne 'print "$1 '$ID' $2\n" if m,^//CALL (ingress|query) (.*),;print "upgrade '$ID' '"$1"' 0x\n" if m,^//CALL upgrade,; ' $2;
[3175](https://github.com/dfinity/motoko/actions/runs/4018188380/jobs/6903492980#step:7:3176)
test-drun-generational-gc> +fi )
[3176](https://github.com/dfinity/motoko/actions/runs/4018188380/jobs/6903492980#step:7:3177)
test-drun-generational-gc> +     14382 Segmentation fault      (core dumped) | drun -c "$CONFIG" --extra-batches $EXTRA_BATCHES /dev/stdin
[3177](https://github.com/dfinity/motoko/actions/runs/4018188380/jobs/6903492980#step:7:3178)
```

**Review by ggreif — APPROVED** [review]
Sounds like a nice canary. I'll monitor the progress.

**Pull request merged**
