### PR TITLE
Rename Con module to Cons

### PR DESCRIPTION
**Pull request by rossberg**
...to work around Windows' name-challenged file system.

I wanted to do this for a long time, but finally got too tired of the constant error messages during my backups. :)

### CODE REVIEW

**Review by ggreif — APPROVED** [review]
Looks rather mechanical, OK!

**Comment by rossberg** [comment]
Yes, it's completely mechanical.

**Comment by crusso** [comment]
You didn't name it PRN then?

**Review by crusso — APPROVED** [review]
Less likely to insult french people too,.

**Pull request merged**
