### PR TITLE
Minor cleanup: Remove some compiler and checker warnings

### PR DESCRIPTION
**Pull request by luc-blaeser**
Cosmetics:
* Eliminate some warnings in rts test compilation
* Resolve some warnings provided by clippy checker

### CODE REVIEW

**Review by nomeata — APPROVED** [review]

**Comment by crusso** [comment]
I can confirm that this removes all the warnings from the real-world scenario I had....

**Comment by nomeata** [comment]
> In terms of gas, 4 tests regressed and the mean change is +1.0%.

Is that expected for a minor cleanup?

**Comment by luc-blaeser** [comment]
Strange, as it actually does not change any productive logic. Need to analyze this next week...

**Comment by nomeata** [comment]
Differential CI is quite useful sometimes :-)

**Comment by luc-blaeser** [comment]
Indeed. I create a new PR for partially reverting this with disabling the checker warning: https://github.com/dfinity/motoko/pull/3554/files 
Very sorry for this inconvenience.

**Pull request merged**
