### PR TITLE
Bump up MAX_HP_FOR_GC from 1GB to 3GB

### PR DESCRIPTION
**Pull request by ulan**
I think the plan was to get initial version with 1GB, then
bump it up to 3G, and then implement more advanced heuristic.

The motivation: there is a spike of messages that dirty between
256MB and 512MB of memory. One theory is that these messages
are from Motoko canisters that crossed the 1GB threshold.

### CODE REVIEW

**Comment by osa1** [comment]
Canisters that allocate at a slow rate but allocate large amounts every once in a while rely on this parameter to have enough allocation are for the calls with large allocations. A larger MAX_HP_FOR_GC will make it more likely for those canisters to get stuck. I have no objections if we're OK with this.

Perhaps in the long run it would make sense to allow configuring these parameters. We could even do it in runtime, maybe with a compiler-generated upgrade method (which would also help with getting a canister unstuck), or provide a prim and let the user to define the endpoint if they feel the need.

Since a larger MAX_HP_FOR_GC is more risky (may cause some canisters to get stuck), I wonder if we should think about possible recovery strategies before merging?

> The motivation: there is a spike of messages that dirty between 256MB and 512MB of memory. One theory is that these messages are from Motoko canisters that crossed the 1GB threshold.

Is the spike for just one message? If a canister passes 1 GiB threshold and dirties 256-512 MiB of memory, that means half of the space is reclaimed, and for the next few messages it shouldn't do GC (assuming it allocates at the same rate as before).

**Comment by osa1** [comment]
(Restarted failing CI job)

**Comment by osa1** [comment]
I wasn't aware that this is labeled as "automerge-squash". I think we should revert this since this will make it more likely for canisters to get stuck, and we have no way of recovering such canisters.

Any thoughts on this? @crusso @ggreif @ulan

**Comment by osa1** [comment]
We discussed this with @ulan. Here's my summary of the problem and what we want to do:

- `MAX_HEAP_FOR_GC = 1 GiB` is too low. It is common for canisters to have live data more than 1 GiB, and in those cases doing GC after every update message causes performance problems. (mainly on the replica, but maybe uses too many cycles too)

- This PR increases `MAX_HEAP_FOR_GC` to 3 GiB. This makes it more likely for canisters to get stuck. With this change, when a canisters reaches 3 GiB heap it will have 1 GiB allocation area for the next query message. Less than that for the next update message because it will want to do GC after the update message.

- We are OK with giving canisters 1 GiB allocation space when their heap size reaches 3 GiB. (not sure what the reasoning here is, perhaps @ulan can say more)

- However, the current default GC (copying) copies all live data to a new space and then back. So with this change, a canister with 3 GiB heap can have at most 1 GiB of live data (less depending on how much it allocates in the last message). This case is probably not too uncommon, so we want to revert this PR for now.

One possible way forward here is making the compacting GC the default. With compacting GC, we need to allocate a bitmap (one bit per heap word), and a growable mark stack. This makes it less likely for canisters with 3 GiB heap size to get stuck.

Compacting GC uses more cycles (~30% last time I benchmarked), but halves dirtied pages, and large dirtied pages is what causes problems on the replica side. So we're OK with trading cycles for less dirtied pages.

Before making compacting GC the default we want to test it more. One idea is to backport random heap generation in #2706.

For now we revert this. We should merge this with the PR that makes compacting GC the default.

**Comment by osa1** [comment]
In addition to my comment above, we discussed about the actual costs of GC algorithms for the platform. Ulan says one dirtied page costs the same as between 10,000 and 100,000 cycles to the replica. If we take that into account in GC benchmarks, I think compacting GC may be significantly faster than the copying GC.

I don't have the raw data for the latest version of the compacting GC and copying GC so I will have to repeat the benchmarks for this.

**Comment by rossberg** [comment]
I agree that we should make compacting GC the default as soon as we think it's safe to do so.

In the meantime, would it make sense to bump max HP to 2GiB (or something slightly less)? Would that avoid the risk of getting stuck?

**Comment by nomeata** [comment]
Compacting might be better than copying, but even that is not really a viable solution; didn't we conclude that only a non-moving incremental GC actually works on the IC? Has work in that direction started? Or at least, do we know which design to work towards?

**Comment by rossberg** [comment]
Yes, we definitely want an incremental generational collector, and we (Ömer) is busy working towards that. I don't know that we concluded non-moving is required (or desired), but Ömer is currently implementing a page-based heap as a prerequisite for the next steps. With that, GC would mostly operate on one page at a time in the end.

**Comment by nomeata** [comment]
Ok, fair enough, incremental might be good enough even if moving.

**Pull request merged**
