### PR TITLE
bugfix: fix bug affecting `--experimental-rtti`

### PR DESCRIPTION
**Pull request by crusso**
I introduced a bug when making rtti a compiler option.

In particular, in `compile.ml`, the value `BigNum.tag_padded` did not test the new compiler flag properly - it was missing the conventional `env` argument and produced code that was failing to tag compact `Int` and `Nat` values (doing a logical or with the non-rtti tag, i.e. 0).

It would probably be safer to read the flag from the env argument, not directly from `Flags`, but that can come in a follow-on PR.

The good news is that the bug is benign for vanilla moc (and we don't even advertise `--experimental-rtti`)

Ì told you it was experimental.

### CODE REVIEW

**Review by luc-blaeser — APPROVED** [review]
Good analysis. Luckily, it only affected the experimental mode.
I agree, putting the flag behind `env` would be more robust.

**Review by ggreif — APPROVED** [review]
Nice find. This was a sneaky one...

**Review by ggreif — COMMENTED** [review]
I fixed the `.ok` file

**Comment by crusso** [comment]
I've opened #4440 for good measure (run CI with rtti enabled by default)

**Pull request merged**
