### PR TITLE
Reproducibility: Make assertion error messages reproducible

### PR DESCRIPTION
**Pull request by crusso**
Our builds are not reproducible because the filepaths reported in assert messages are build environment dependent.

A simple fix is to only report the basename of the file in the assertion message, though this loses some information and may be ambiguous if a  project imports two distinct files with the same basename (this is possible, but not that likely, given the current scale of motoko projects.)

A better approach my be to relativize the source file to the current main file or package, but this probably requires pervasive changes to our Source.ml region representation, or other measures, like storing the root dir in the compilation unit.

TODO:

- [ ] normalize to base name in interpretation of AssertE (both source and IR interpreters), if we care about that level of fidelity.

### CODE REVIEW

**Review by nomeata — APPROVED** [review]
Reasonable way forward. Relative to project or package root is probably better, but maybe not worth the complexity at this point.

**Comment by osa1** [comment]
> A better approach my be to relativize the source file to the current main file or package

I agree. How do we show paths from imported libraries currently? I'm guessing something like  `../../../motoko-base/src/Hash.mo:123:456 ...`? If that's the case then I think this PR could be a step backwards, because just showing `Hash.mo:...` will probably be confusing: user may have a file with the same name in the project, or may get confused about where that file is.

I wonder if we could also refactor the `region` type a little bit:

```
type pos = {file : string; line : int; column : int}
type region = {left : pos; right : pos}
```

The problem is this allows invalid region representations where start and end of the region have different files.

**Review by rossberg — APPROVED** [review]
Agreed this is a regression yet okayish for now. I suspect that a nicer fix would be rather non-trivial. (It's perhaps representative of the kind of rabbit holes you get into with the goal of reproducible builds. ;) )

**Comment by crusso** [comment]
> > A better approach my be to relativize the source file to the current main file or package
> 
> I agree. How do we show paths from imported libraries currently? I'm guessing something like `../../../motoko-base/src/Hash.mo:123:456 ...`? If that's the case then I think this PR could be a step backwards, because just showing `Hash.mo:...` will probably be confusing: user may have a file with the same name in the project, or may get confused about where that file is.
> 
> I wonder if we could also refactor the `region` type a little bit:
> 
> ```
> type pos = {file : string; line : int; column : int}
> type region = {left : pos; right : pos}
> ```
> 
> The problem is this allows invalid region representations where start and end of the region have different files.

Yeah, I'm not sure why its like this - the code was copied from the wasm reference implementation I think, except perhaps to avoid even more allocation when constructing a region or projecting a position.

**Comment by rossberg** [comment]
I reused the definition of source region from an older project of mine. The definition is so because there might have been a file inclusion mechanism, such that left and right of a region may indeed be in separate files.

**Comment by oggy-dfin** [comment]
@crusso confirmed that this fixes the issue compared to the `moc` from the old master

**Comment by skilesare** [comment]
Copying this from a conversation with Claudio on the Forum

Privacy issue about the motoko compiler. If you go to Principal wm2oc-maaaa-aaaah-qb47a-cai  on https://ic.rocks/principal/wm2oc-maaaa-aaaah-qb47a-cai and look at the getFiles function, it will fail. The error message leaks information about the person who compiled the module. Who is nandit? I don’t know, but perhaps they do not want their name in the error message? You can move to a different folder without personal info, but maybe people don’t know that. 

Some kind of relative path make sense here...bonus if it makes it deterministic for all compilers.

**Pull request merged**
