### PR TITLE
Add `Prim.principalOfBlob()`

### PR DESCRIPTION
**Pull request by nomeata**
It’s silly to have `Principal.toBlob()`, but not the other direction.

### CODE REVIEW

**Comment by ggreif** [comment]
I assume all `Principal`s are checked for well-formedness on the system boundary entry?

**Comment by crusso** [comment]
Are there really no restrictions on the binary format of a principal that we should check?

**Comment by nomeata** [comment]
The only meaningful might be the length (at most 29 bytes), but so far we treat them completely opaque, including in our other intro form so far, namely `actor "…"`. And for all principals from the system we trust that the limit holds.

This is ok; too long principals are a bit like non-existent principals?

Interestingly, we _do_ check the length in Candid decoding. But that’s because there it’s untrustworthy input.

We could make it an invariant in Motoko that `Principal` is short. Not sure if it’s worth it.

**Comment by crusso** [comment]
In that case, fire away.

**Review by crusso — APPROVED** [review]
LGTM (FWIW)

**Pull request merged**
