### PR TITLE
Test `rustc` upgrade

### PR DESCRIPTION
**Pull request by luc-blaeser**
Generational GC seems to schedule at somewhat different points in the tests and thus occasionally exceed the limit for certain tests (that were already close at the limit before). In debug mode, the generational GC performs extensive full-heap sanity checks.

### CODE REVIEW

**Comment by ggreif** [comment]
This is green now. Do you want to tweak the numbers further?

Anyway, thanks for doing this!

**Comment by ggreif** [comment]
Question: where does the -3.8% size change come from?

**Review by ggreif — APPROVED** [review]
Thanks for figuring this out!

**Comment by luc-blaeser** [comment]
> Question: where does the -3.8% size change come from?

I am not sure: Maybe it is due to some optimizations in the new Rust compiler. But this would need to be analyzed.

**Comment by ggreif** [comment]
Let's see if those 3.8% also happen on the parent branch :-)

**Pull request merged**
