### PR TITLE
test: disable sanity checking for ic-ref

### PR DESCRIPTION
**Pull request by crusso**
This turns off the now very heavy duty GC sanity checking when targeting `ic-ref` where it's too painfully slow (but not for `drun`!). Brings our CI times down to a more manageable 1.25 hr, not 3-4hrs.

### CODE REVIEW

**Comment by crusso** [comment]
@luc-blaeser: let's see if this helps without throwing too much caution to the wind

**Comment by crusso** [comment]
That seems more reasonable. I hope I didn't turn off all the sanity checks, just ic-ref

**Review by luc-blaeser — APPROVED** [review]
Great. Looks very good. I also verified, that it only disables debug assertions during `ic-ref-run`. This will substantially speed up CI and development. Many thanks.

**Review by ggreif — APPROVED** [review]
I agree that sanity-checking should only run on the fastest platform we have. Thanks!

**Review by nomeata — COMMENTED** [review]
How did CI times grow so out of bounds! 

Ha, I didn't know we still had the flag to distinguish these.

But this still runs all the test again for sanity checking just without the tests. I'd be cleaner to adjust run.sh to skip ic-ref in these jobs. Or rather, just don't generate the corresponding job in the nix file

**Comment by crusso** [comment]
> 



> How did CI times grow so out of bounds!
> 
> Ha, I didn't know we still had the flag to distinguish these.
> 
> But this still runs all the test again for sanity checking just without the tests. I'd be cleaner to adjust run.sh to skip ic-ref in these jobs. Or rather, just don't generate the corresponding job in the nix file

That does sound better, but I don't have the time to do that today and perhaps not soon. Any takers?

**Comment by nomeata** [comment]
I had a look, but it seems that already there is no `ic-ref-dbg` job defined in
```
  in fix_names ({
      run        = test_subdir "run"        [ moc ] ;
      run-dbg    = snty_subdir "run"        [ moc ] ;
      ic-ref-run = test_subdir "run-drun"   [ moc ic-ref-run ];
      ic-ref-run-compacting-gc = compacting_gc_subdir "run-drun" [ moc ic-ref-run ] ;
      ic-ref-run-generational-gc = generational_gc_subdir "run-drun" [ moc ic-ref-run ] ;
      drun       = test_subdir "run-drun"   [ moc nixpkgs.drun ];
      drun-dbg   = snty_subdir "run-drun"   [ moc nixpkgs.drun ];
      drun-compacting-gc = compacting_gc_subdir "run-drun" [ moc nixpkgs.drun ] ;
      drun-generational-gc = generational_gc_subdir "run-drun" [ moc nixpkgs.drun ] ;
      fail       = test_subdir "fail"       [ moc ];
      repl       = test_subdir "repl"       [ moc ];
      ld         = test_subdir "ld"         ([ mo-ld ] ++ ldTestDeps);
      idl        = test_subdir "idl"        [ didc ];
      mo-idl     = test_subdir "mo-idl"     [ moc didc ];
      trap       = test_subdir "trap"       [ moc ];
      run-deser  = test_subdir "run-deser"  [ deser ];
      perf       = perf_subdir "perf"       [ moc nixpkgs.drun ];
      bench      = perf_subdir "bench"      [ moc nixpkgs.drun ];
      viper      = test_subdir "viper"      [ moc nixpkgs.which nixpkgs.openjdk nixpkgs.z3 ];
      inherit qc lsp unit candid profiling-graphs coverage;
    }) // { recurseForDerivations = true; };
```

Are you worried about CI times, or local `make check `times?

**Comment by crusso** [comment]
> I had a look, but it seems that already there is no `ic-ref-dbg` job defined in
> 
> ```
>   in fix_names ({
>       run        = test_subdir "run"        [ moc ] ;
>       run-dbg    = snty_subdir "run"        [ moc ] ;
>       ic-ref-run = test_subdir "run-drun"   [ moc ic-ref-run ];
>       ic-ref-run-compacting-gc = compacting_gc_subdir "run-drun" [ moc ic-ref-run ] ;
>       ic-ref-run-generational-gc = generational_gc_subdir "run-drun" [ moc ic-ref-run ] ;
>       drun       = test_subdir "run-drun"   [ moc nixpkgs.drun ];
>       drun-dbg   = snty_subdir "run-drun"   [ moc nixpkgs.drun ];
>       drun-compacting-gc = compacting_gc_subdir "run-drun" [ moc nixpkgs.drun ] ;
>       drun-generational-gc = generational_gc_subdir "run-drun" [ moc nixpkgs.drun ] ;
>       fail       = test_subdir "fail"       [ moc ];
>       repl       = test_subdir "repl"       [ moc ];
>       ld         = test_subdir "ld"         ([ mo-ld ] ++ ldTestDeps);
>       idl        = test_subdir "idl"        [ didc ];
>       mo-idl     = test_subdir "mo-idl"     [ moc didc ];
>       trap       = test_subdir "trap"       [ moc ];
>       run-deser  = test_subdir "run-deser"  [ deser ];
>       perf       = perf_subdir "perf"       [ moc nixpkgs.drun ];
>       bench      = perf_subdir "bench"      [ moc nixpkgs.drun ];
>       viper      = test_subdir "viper"      [ moc nixpkgs.which nixpkgs.openjdk nixpkgs.z3 ];
>       inherit qc lsp unit candid profiling-graphs coverage;
>     }) // { recurseForDerivations = true; };
> ```
> 
> Are you worried about CI times, or local `make check `times?

It was CI times. I think the issue is that the compacting_gc_subdir and generational_gc_subdir  both specify --sanity so we just need to define non-sanity versions of those for ic-ref.

**Comment by crusso** [comment]
@luc-blaeser @nomeata @ggreif PTAL

**Review by nomeata — APPROVED** [review]

**Review by ggreif — APPROVED** [review]
Makes sense. I like this less entangled solution more. Thanks!

**Comment by luc-blaeser** [comment]
I also think this is a pragmatic solution. Thanks.

**Pull request merged**
