### PR TITLE
chore: no need for the `release` branch any more

### LINKED ISSUE #3312: What is the `release` branch for?
When looking at  `Building.md` it seems that the only purpose of the `release` branch is to push Motoko labels.

But we could do that for master too, or just `git push --tag`.

I am asking because `release` seems to have received a stray commit, and I can't repair the situation. Everything else seems to work, so maybe we can sunset the `release` branch.

### PR DESCRIPTION
**Pull request by ggreif**
Fixes #3312.

### CODE REVIEW

**Review by nomeata — APPROVED** [review]

**Review by crusso — APPROVED** [review]
Thanks for  sorting this out!

**Comment by nomeata** [comment]
Looks like I got again kicked off the repo…

**Comment by ggreif** [comment]
Me too, cannot add label :-(

**Comment by nomeata** [comment]
That’s weird, it isn’t even Friday

**Comment by ggreif** [comment]
Looks like some permission changes are coming up.

**Comment by crusso** [comment]
> Looks like I got again kicked off the repo…

I'm asking for write access for you (same as me, to be fair)

**Pull request merged**
