### PR TITLE
Codegen: remove unused instructions in size_alias

### PR DESCRIPTION
**Pull request by osa1**

### CODE REVIEW

**Comment by osa1** [comment]
I think this line was a copy-paste error

**Review by nomeata — COMMENTED** [review]
Hmm, that's the argument to the Or two lines down, isn't it?

**Comment by osa1** [comment]
Hm, you are right. Interestingly I didn't get any errors when running the Wasm generated with this change. I would expect this to break the stack by popping one more value than before.

**Comment by nomeata** [comment]
That is odd indeed, worth investigating. Are we exiting this via return? … No. Weird.

**Comment by ggreif** [comment]
I checked this code a few days ago, it is okay. One could perform 4x `get_tag ^^ compile_eq_const` and the 3x `Or`. But I think it is fine as-is.

**Pull request closed without merging**
