### PR TITLE
word mix-up

### PR DESCRIPTION
**Pull request by cPlayIt**
I believe destructured is the correct word here.

### CODE REVIEW

**Review by crusso — COMMENTED** [review]
I actually prefer deconstructed since destructuring implies destruction of the original value (which is not the case).

@rossberg?

**Comment by cPlayIt** [comment]
Destructuring assignment is a specialized term in JavaScript and PHP
documentation, however I am not familiar with how things are represented in
other languages.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment
https://www.php.net/manual/en/migration71.new-features.php#migration71.new-features.symmetric-array-destructuring

**Comment by rossberg** [comment]
"Destructuring" is the established term in a number of communities, so I'm fine with using it.

**Comment by crusso** [comment]
Superseeded by #2620

**Pull request closed without merging**
