### PR TITLE
chore: update docs

### PR DESCRIPTION
**Pull request by ggreif**

### CODE REVIEW

**Comment by jessiemongeon1** [comment]
It looks like the revised URL leads to a broken page, while the current URL leads to the expected page on Candid serialization.

**Comment by ggreif** [comment]
@jessiemongeon1 so this should better not go in, right?

**Comment by ggreif** [comment]
I wonder where the stale link comes from, then.

**Comment by jessiemongeon1** [comment]
@ggreif Correct

**Review by dfx-json — APPROVED** [review]

**Pull request merged**
