### PR TITLE
Tweak Haskell imports

### PR DESCRIPTION
**Pull request by ggreif**

### CODE REVIEW

**Review by ggreif — COMMENTED** [review]
This is just a silly test of the modified Mergify config.

**Review by nomeata — APPROVED** [review]

**Comment by ggreif** [comment]
@nomeata looks like mergify adds itself as a co-author now when merging to `master`. I am not sure what I messed up here.

**Comment by nomeata** [comment]
Is this new behavior?

**Comment by ggreif** [comment]
Looks like this happens when there is no PR description. It occurred several times already in the past. I'll watch this.

**Pull request merged**
