### PR TITLE
Integrate Regions in Random GC Tests

### PR DESCRIPTION
**Pull request by luc-blaeser**
Extending the random GC tests to also allocate regions. 
The same tests can also be used for long-running and larger-scaling tests. 
Therefore, the maximum number of randomly created regions is limited - until region garbage collection will be supported.

### CODE REVIEW

**Comment by matthewhammer** [comment]
Thanks @luc-blaeser !

**Comment by crusso** [comment]
Ohoh, we never review nor merged this? Shall I take another look @luc-blaeser?

**Comment by luc-blaeser** [comment]
> Ohoh, we never reviewed nor merged this? Shall I take another look @luc-blaeser?

No worries. This is only an extended test case. I reran the tests after a recent merge. If it passes, you may take another look. Thanks a lot.

**Review by crusso — APPROVED** [review]
LGTM, never hurts to have more testing.

**Pull request merged**
