### PR TITLE
Bump drun

### PR DESCRIPTION
**Pull request by nomeata**

### CODE REVIEW

**Comment by nomeata** [comment]
Hmm, something seems to be in a bad shape: The `drun` tests now hangs, seemingly at test `basic-cycles`. 

CPU consumption is not high, so it seems to have deadlocked.

Any ideas, @ulan? Too bad that we couldn’t bump `drun` for so long, this will make guessing which commit causes this hard.

**Comment by ulan** [comment]
> Any ideas, @ulan? Too bad that we couldn’t bump `drun` for so long, this will make guessing which commit causes this hard.

No idea. I would have to debug this. How can I reproduce it locally (which files to pass to `drun`)?

**Comment by nomeata** [comment]
Here is a way to reproduce, with already more insight:

```
/tmp/drun-hangs $ drun -c drun.json5 --extra-batches 1 script.drun 
ingress Completed: Reply: 0x4449444c016c01b3c4b1f204680100010a00000000000000000101
ingress Completed: Reply: 0x4449444c0000
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] IC0503: Canister rwlgt-iiaaa-aaaaa-aaaaa-cai trapped explicitly: cannot add more than 2^128 cycles
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] ok
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] IC0503: Canister rwlgt-iiaaa-aaaaa-aaaaa-cai trapped explicitly: cannot add more than 2^128 cycles
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] IC0503: Canister rwlgt-iiaaa-aaaaa-aaaaa-cai trapped explicitly: cycles out of bounds
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] {balance = 100_000_000_000_000}
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] {topped_up_balance = 100_000_000_000_000}
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] {added = 0}
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] {amount = 0; available = 0}
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] {balance = 100_000_000_000_000}
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] {topped_up_balance = 100_000_000_000_000}
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] {added = 4_294_967_295}
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] {amount = 4_294_967_295; available = 4_294_967_295}
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] {balance = 100_000_000_000_000}
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] {topped_up_balance = 18_446_744_073_709_551_615}
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] {added = 18_446_744_073_709_551_615}
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] {amount = 18_446_744_073_709_551_615; available = 18_446_744_073_709_551_615}
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] {balance = 18_446_744_073_709_551_615}
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] {topped_up_balance = 18_446_744_073_709_551_616}
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] {added = 18_446_744_073_709_551_616}
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] {amount = 18_446_744_073_709_551_616; available = 18_446_744_073_709_551_616}
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] {balance = 18_446_744_073_709_551_616}
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] {topped_up_balance = 79_228_162_514_264_337_593_543_950_335}
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] {added = 79_228_162_514_264_337_593_543_950_335}
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] {amount = 79_228_162_514_264_337_593_543_950_335; available = 79_228_162_514_264_337_593_543_950_335}
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] {balance = 79_228_162_514_264_337_593_543_950_335}
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] {topped_up_balance = 340_282_366_920_938_463_463_374_607_431_768_211_455}
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] {added = 340_282_366_920_938_463_463_374_607_431_768_211_455}
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: TryFromIntError(())', system_api/src/sandbox_safe_system_state.rs:331:88
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Sandbox pid 128292 for canister Some(CanisterId(rwlgt-iiaaa-aaaaa-aaaaa-cai)) exited unexpectedly with status Signaled(Pid(128292), SIGABRT, true)
thread '<unnamed>' panicked at 'Launcher detected sandbox exit', canister_sandbox/sandbox_launcher/src/lib.rs:121:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'Error from launcher process, pid 128279 exited due to signal!', canister_sandbox/replica_controller/src/sandboxed_execution_controller.rs:910:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
(now it just sits for a while)
thread 'main' panicked at 'Ingress message did not finish executing within 10000 batches, panicking', drun/src/lib.rs:363:5
(still sitting)
^C
```

All needed to reproduce is here: [drun-hangs.zip](https://github.com/dfinity/motoko/files/8428841/drun-hangs.zip)

**Comment by crusso** [comment]
@nomeata thanks for that!

**Comment by ulan** [comment]
Thanks @nomeata!

**Comment by crusso** [comment]
I wonder if there was some change in the replica's `provisional_top_up_actor`

**Comment by crusso** [comment]
This is the code for the test:
```
// test cycle overflow detection and larger cycle transfers

import Prim "mo:⛔";

actor a {

  let balance : () -> Nat = Prim.cyclesBalance;
  let available : () -> Nat = Prim.cyclesAvailable;
  let accept : Nat-> Nat = Prim.cyclesAccept;
  let add : Nat -> () = Prim.cyclesAdd;

  let refunded : () -> Nat = Prim.cyclesRefunded;


  public func provisional_top_up_actor(a : actor {}, amount : Nat) : async () {
    let amount_ = amount;
    let ic00 = actor "aaaaa-aa" : actor {
      provisional_top_up_canister :
        { canister_id: Principal; amount : Nat } -> async ();
    };
    await ic00.provisional_top_up_canister({
      canister_id = Prim.principalOfActor(a);
      amount = amount_})
  };


  public func test(amount : Nat) : async () {
     Prim.debugPrint(debug_show({available=available(); amount = amount}));
     assert (available() == amount);
  };

  // test overflow of 128 bit cycle amounts
  public func overflow() : async () {

     // detect immediate overflow of add
     try (await async {
       add(0x1_00000000_00000000_00000000_00000000);
       assert false;
     })
     catch (e) {Prim.debugPrint(Prim.errorMessage(e))};

     // detect incremental overflow of add
     try (await async {
       add(0xFFFFFFFF_FFFFFFFF_FFFFFFFFF_FFFFFFF);
       Prim.debugPrint("ok");
       add(0x1);
       assert false;
     })
     catch (e) { Prim.debugPrint(Prim.errorMessage(e)) };

     // detect accept overflow
     try (await async {
       let _ = accept(0x1_00000000_00000000_00000000_00000000);
       assert false;
     })
     catch (e) { Prim.debugPrint(Prim.errorMessage(e)) };

  };

  var tests = [
     0x0,
     0xFFFFFFFF,
     0xFFFFFFFF_FFFFFFFF,
     0x1_00000000_00000000,
     0xFFFFFFFF_FFFFFFFF_FFFFFFFF,
     0xFFFFFFFF_FFFFFFFF_FFFFFFFF_FFFFFFFF,
  ];

  public func iter() : async () {

     for (amount in tests.vals()) {
       Prim.debugPrint(debug_show {balance = balance()});
       if (balance() < amount) {
         await provisional_top_up_actor(a, amount - balance());
       };
       Prim.debugPrint(debug_show {topped_up_balance = balance()});
       if (amount > balance()) {
         Prim.debugPrint("can't top up more");
         return; // give up on test
       };
       add(amount);
       Prim.debugPrint(debug_show({added = amount}));
       try {
         await test(amount);
       } catch e {
         Prim.debugPrint(Prim.errorMessage(e));
       }
     }
  };

  public func go() : async (){
    await overflow();
    await iter();
  }
};

a.go(); //OR-CALL ingress go "DIDL\x00\x00"
//SKIP run
//SKIP run-ir
//SKIP run-low
```
And the error that used to occur was user error "can't top up more"...

**Comment by ulan** [comment]
> I wonder if there was some change in the replica's `provisional_top_up_actor`

I found this change that adds support for 128-bit cycles there: https://github.com/dfinity/ic/commit/041b6caf9ad25c18049e5205b66269f438375346

I'll talk with the execution team and we'll prepare a fix tomorrow.

**Comment by crusso** [comment]
Just a hunch, but perhaps related to this https://github.com/dfinity/ic/commit/2a81bc02301e58bbc1477497af21a8ca3df2a29a?

**Comment by nomeata** [comment]
That would be the commit that makes it go further, but probably not the commit that makes `drun` fail to exit gracefully at the end; that’s more likely the introduction of the sandbox itself. But I’m sure the execution team can bisect that in no time :)

**Comment by ulan** [comment]
It was indeed introduced by sandboxing which uses signed 128-bit integers to keep track of the cycle changes.
The fix I have in mind is to ensure that the maximum canister balance fits into signed 128-bit integer.

**Comment by nomeata** [comment]
Ah, the problem is signed 128 vs. unsigned 128? Why even used signed integers there?

**Comment by ulan** [comment]
> Ah, the problem is signed 128 vs. unsigned 128? Why even used signed integers there?

Yes. Sandboxed execution returns a delta of the system state and signed integers were probably the simplest solution. An alternative would be to use two fields: `cycles_added` and `cycles_removed`. We could also change the meaning of "delta" and return the latest balance there.

**Comment by nomeata** [comment]
@ulan, can I disable the sanbdoxed execution, maybe via the config file? Then we can at least bump `drun`, and maybe catch other issues. We can enable it when it works again.

**Comment by nomeata** [comment]
Indeed, I can add
```
  hypervisor: {
    canister_sandboxing_flag: "Disabled",
  },
```
to the config, and now I get

```
/tmp/drun-hangs $ drun -c drun.json5 --extra-batches 1 script.drun 
ingress Completed: Reply: 0x4449444c016c01b3c4b1f204680100010a00000000000000000101
ingress Completed: Reply: 0x4449444c0000
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] IC0503: Canister rwlgt-iiaaa-aaaaa-aaaaa-cai trapped explicitly: cannot add more than 2^128 cycles
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] ok
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] IC0503: Canister rwlgt-iiaaa-aaaaa-aaaaa-cai trapped explicitly: cannot add more than 2^128 cycles
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] IC0503: Canister rwlgt-iiaaa-aaaaa-aaaaa-cai trapped explicitly: cycles out of bounds
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] {balance = 100_000_000_000_000}
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] {topped_up_balance = 100_000_000_000_000}
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] {added = 0}
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] {amount = 0; available = 0}
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] {balance = 100_000_000_000_000}
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] {topped_up_balance = 100_000_000_000_000}
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] {added = 4_294_967_295}
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] {amount = 4_294_967_295; available = 4_294_967_295}
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] {balance = 100_000_000_000_000}
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] {topped_up_balance = 18_446_744_073_709_551_615}
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] {added = 18_446_744_073_709_551_615}
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] {amount = 18_446_744_073_709_551_615; available = 18_446_744_073_709_551_615}
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] {balance = 18_446_744_073_709_551_615}
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] {topped_up_balance = 18_446_744_073_709_551_616}
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] {added = 18_446_744_073_709_551_616}
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] {amount = 18_446_744_073_709_551_616; available = 18_446_744_073_709_551_616}
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] {balance = 18_446_744_073_709_551_616}
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] {topped_up_balance = 79_228_162_514_264_337_593_543_950_335}
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] {added = 79_228_162_514_264_337_593_543_950_335}
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] {amount = 79_228_162_514_264_337_593_543_950_335; available = 79_228_162_514_264_337_593_543_950_335}
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] {balance = 79_228_162_514_264_337_593_543_950_335}
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] {topped_up_balance = 340_282_366_920_938_463_463_374_607_431_768_211_455}
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] {added = 340_282_366_920_938_463_463_374_607_431_768_211_455}
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: TryFromIntError(())', system_api/src/sandbox_safe_system_state.rs:331:88
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'MR Batch Processor' panicked at 'Thread pool worker panicked', /build/drun-vendor.tar.gz/scoped_threadpool/src/lib.rs:236:13
thread 'main' panicked at 'Failed to send batch 30: background worker is dead', messaging/src/message_routing.rs:1014:51
```
so it does exit, but it still hits the bug in `system_api/src/sandbox_safe_system_state.rs`. Guess we’ll have to wait for the fix.

**Comment by ulan** [comment]
Indeed this code is shared between sandboxed and non-sandboxed execution.

The fix is in review. I'll try to merge it as soon as possible.

**Comment by ulan** [comment]
The result of the fixed drun:
```
ingress Completed: Reply: 0x4449444c016c01b3c4b1f204680100010a00000000000000000101
ingress Completed: Reply: 0x4449444c0000
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] IC0503: Canister rwlgt-iiaaa-aaaaa-aaaaa-cai trapped explicitly: cannot add more than 2^128 cycles
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] ok
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] IC0503: Canister rwlgt-iiaaa-aaaaa-aaaaa-cai trapped explicitly: cannot add more than 2^128 cycles
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] IC0503: Canister rwlgt-iiaaa-aaaaa-aaaaa-cai trapped explicitly: cycles out of bounds
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] {balance = 100_000_000_000_000}
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] {topped_up_balance = 100_000_000_000_000}
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] {added = 0}
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] {amount = 0; available = 0}
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] {balance = 100_000_000_000_000}
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] {topped_up_balance = 100_000_000_000_000}
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] {added = 4_294_967_295}
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] {amount = 4_294_967_295; available = 4_294_967_295}
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] {balance = 100_000_000_000_000}
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] {topped_up_balance = 18_446_744_073_709_551_615}
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] {added = 18_446_744_073_709_551_615}
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] {amount = 18_446_744_073_709_551_615; available = 18_446_744_073_709_551_615}
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] {balance = 18_446_744_073_709_551_615}
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] {topped_up_balance = 18_446_744_073_709_551_616}
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] {added = 18_446_744_073_709_551_616}
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] {amount = 18_446_744_073_709_551_616; available = 18_446_744_073_709_551_616}
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] {balance = 18_446_744_073_709_551_616}
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] {topped_up_balance = 79_228_162_514_264_337_593_543_950_335}
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] {added = 79_228_162_514_264_337_593_543_950_335}
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] {amount = 79_228_162_514_264_337_593_543_950_335; available = 79_228_162_514_264_337_593_543_950_335}
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] {balance = 79_228_162_514_264_337_593_543_950_335}
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] {topped_up_balance = 340_282_366_920_938_463_463_374_607_431_768_211_455}
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] {added = 340_282_366_920_938_463_463_374_607_431_768_211_455}
[Canister rwlgt-iiaaa-aaaaa-aaaaa-cai] {amount = 340_282_366_920_938_463_463_374_607_431_768_211_455; available = 340_282_366_920_938_463_463_374_607_431_768_211_455}
ingress Completed: Reply: 0x4449444c0000
```

**Comment by ulan** [comment]
The fix is merged: https://github.com/dfinity/ic/commit/a2e8b5b1699faa916a4ee1b522f3891b1f98a5fd

**Comment by nomeata** [comment]
> In terms of gas, 3 tests regressed and the mean change is +1389.2%.

Heh, the new cycle costs for system calls show up.

Anyways, this is finally green and good to merge.

**Comment by nomeata** [comment]
Can I haz approval for this?

**Review by crusso — APPROVED** [review]
Sorry about the delay...

**Pull request merged**
