### PR TITLE
Improve support for navigating to definitions in external modules

### PR DESCRIPTION
**Pull request by rvanasa**
I rewrote most of `definition_handler` to account for edge cases related to finding definitions in external files. 

- It's now possible to jump to the definition of an import identifier (rather than having to click on a qualified member name). For example, `import M|ap "HashMap"` (where `|` is the cursor) jumps to the top of `HashMap.mo` instead of doing nothing (fixes dfinity/vscode-motoko#17). 

- The new implementation also has a more permissive default behavior for missing declarations. In cases where the module path is known but the qualified symbol is unknown, the language server attempts to direct the user to the relevant module. This is mostly intended as a fallback for situations where the index is missing an expected declaration, such as when the other file has a syntax error. 

Possible future improvements:

- Using the start/end position of the `module` or equivalent keyword (when possible) rather than the top of the file
- Providing the same functionality when the cursor is on the import string literal (and perhaps even the `import` keyword)
- Supporting object pattern-style imports as mentioned in #3078 (currently experimenting with this)

Passes all tests on my WSL setup and works as expected in VSCode with the [official Motoko extension](https://github.com/dfinity/vscode-motoko). 

(@matthewhammer)

### CODE REVIEW

**Comment by matthewhammer** [comment]
Thanks @rvanasa!  I'm adding @crusso and @ggreif as reviewers.

**Comment by matthewhammer** [comment]
cc @kritzcreek

**Review by kritzcreek — COMMENTED** [review]
Haven't looked all that closely but the changes seem reasonable. Either way I'd expect a change like this to also include a test.

**Comment by crusso** [comment]
Hi Ryan, thanks for the PR(s)!

 I'm in the middle of a family emergency so won't get a chance to review today. Hopefully someone else can oblige or I'll get to it in the next few days

**Comment by crusso** [comment]
(merging with master to kick off another build)

**Comment by crusso** [comment]
I'm not sure why this hasn't merged. @rvanasa are you not allowed to merge, even with approval, or were you holding back for #3282 instead?

**Comment by ggreif** [comment]
@rvanasa if you cannot merge, try adding the `automerge-squash` label. If that also fails then we are happy to push the button for you!

**Comment by rvanasa** [comment]
@ggreif it looks like I would need write permissions to add a label to the PR. Thanks for merging when you get the chance!

**Comment by crusso** [comment]
Fab! Thanks again!

**Pull request merged**
