### PR TITLE
CI: Remove hydra files

### LINKED ISSUE #2565: Public CI metaissue
This issue tracks various refinements we want to do to our CI infrastructure post-open source. 

 * [x] https://github.com/dfinity/motoko/issues/2544 Pick a public CI system (Github actions + cachix for now)
 * [x] https://github.com/dfinity/motoko/pull/1224 Set it up
 * [x] https://github.com/dfinity/motoko/issues/2566 Automatically create releases and publish build artifacts there
 * [x] https://github.com/dfinity/motoko/issues/2567 Allow public access to `drun`, so that all tests can be run on CI
       This blocks most of the following items:
 * [ ] https://github.com/dfinity/motoko/issues/2568 Publish reports (profiling, documentation preview) from GitHub Action runs
 * [x] #2740 Report performance changes in comment to PR (maybe using [this Github Action](https://github.com/marketplace/actions/create-or-update-comment#where-to-find-the-id-of-a-comment))
 * [x] #2744 Switch branch protection to Github Action rather than hydra
 * [ ] #2771 Stop using the internal CI system.

### PR DESCRIPTION
**Pull request by nomeata**
this fixes #2565 by removing the remaining files that are only there for
Hydra’s sake, and updates the docs to remove mention of hydra.

### CODE REVIEW

**Comment by nomeata** [comment]
I still see evaluation reports form hydra. Didn’t IDX disable them on August 30? @pikajude? (Or maybe they were removed from the jobset repo, but hydra wasn’t redeployed?)

**Comment by crusso** [comment]
> I still see evaluation reports form hydra. Didn’t IDX disable them on August 30? @pikajude? (Or maybe they were removed from the jobset repo, but hydra wasn’t redeployed?)
> 
> We can still merge this PR and simply ignore the status until hydra stops reporting stuff.

I had a brief look at https://github.com/dfinity-lab/hydra-jobsets and it seems to still contain references to motoko and motoko PR jobs. Not sure how to fix that. Is the idea that we remove all references to motoko?

**Comment by nomeata** [comment]
Yes, hydra no longer needs to know about motoko?

**Comment by crusso** [comment]
@pikajude do you want to purge motoko from https://github.com/dfinity-lab/hydra-jobsets  or would you like me to have a go (though I know not what I am doing and will be flying blind).

**Comment by nomeata** [comment]
In any case someone from IDX will have to redeploy the hydra config, I think, which I assume Claudio won’t be able to do himself.

**Comment by nomeata** [comment]
Hydra is failing anyways, so we can merge this, I think. Maybe that’ll make hydra stop reporting statuses here.

**Comment by nomeata** [comment]
Is the hydra builder still used by Motoko in some form?

**Pull request closed without merging**
