### PR TITLE
grammar fix for `let-else`

### LINKED ISSUE #3864: let-else: `()` cannot produce expected type `None`
> src/oops.mo
```motoko
func oops() : Nat {
  var x = 0;
  loop {
    if (x >= 10) return let y = x else {
      x += 1;
    }
  };
};

assert(oops() == 10);
```
Works in `moc v0.8.2`, breaks in `moc v0.8.3` (`moc -r src/oops.mo`).

### PR DESCRIPTION
**Pull request by crusso**
Builds on repro #3868 for change in semantics of 

`if exp let pat = exp else ...`

- restricts let-else construct to dec production, excluding use as expression
- removes need for precedence declaration.

Seem to preserve old semantics:

```
[nix-shell:~/motoko/test/run]$ rlwrap moc
Motoko compiler (source 0.8.3-14-g6e9f32125-dirty)
> func bar() { if false let _ = 4 else return; assert false};
let bar : () -> () = func
> bar();
> 
```

Fixes #3864

### CODE REVIEW

**Review by luc-blaeser — APPROVED** [review]
Great. I believe this is a very good pragmatic solution to the syntax backwards problem.

**Review by ggreif — APPROVED** [review]
Neat!

**Comment by crusso** [comment]
Let's see if @kentosugama agrees too.

**Review by kentosugama — APPROVED** [review]
LGTM!

**Comment by ggreif** [comment]
Closes #3868.

**Pull request merged**
