### PR TITLE
Multi-value emulation: Use globals, not allocated tuples

### PR DESCRIPTION
**Pull request by nomeata**
So far, the IC does not support wasm using multi-value returns from functions and blocks (see #1459). The backend was originally written with that feature in mind, and later we added a work-around (module `FakeMultiVal`).

For functions we work around it by storing multiple values in fixed globals, and reading them after the call. No allocations needed.

For blocks with multiple values, however, we allocate a tuple (array) on the heap, write the values there, and read them later. This adds unnecessary heap churn and fills up memory faster.

So this PR uses the mechanism from the functions also for blocks.

Goes well with #3556

Here is a (particularly bad) example:

In
```motoko
func multi_value_blocks(n : Nat) : (Nat, Nat) {
  return (
    if (n == 0) {
      returns_tuple()
    } else {
      if (n == 1) {
        returns_tuple()
      } else {
        returns_tuple()
      }
   }
 );
};
```
Now no allocation happens (and all the reads and writes to the global variables are eliminated due to #3556):

```diff
   (func $multi_value_blocks (type 1) (param $clos i32) (param $n i32)
     local.get $n
     i32.const 0
     call $B_eq
-    if (result i32)  ;; label = @1
+    if  ;; label = @1
       i32.const 0
       call $returns_tuple
-      global.get 4
-      global.get 5
-      call $to_2_tuple
     else
       local.get $n
       i32.const 2
       call $B_eq
-      if (result i32)  ;; label = @2
+      if  ;; label = @2
         i32.const 0
         call $returns_tuple
-        global.get 4
-        global.get 5
-        call $to_2_tuple
       else
         i32.const 0
         call $returns_tuple
-        global.get 4
-        global.get 5
-        call $to_2_tuple
       end
     end
-    call $from_2_tuple
     return)
```

### CODE REVIEW

**Review by crusso — COMMENTED** [review]
LGTM, but @ggreif should take a look too.

Will this automatically kick in for switches too, assuming we reduce those to `if_`?

**Comment by ggreif** [comment]
> Will this automatically kick in for switches too, assuming we reduce those to `if_`?

Last time I looked the `switch` result was communicated back via Wasm locals (set by assignment).

**Comment by nomeata** [comment]
> Last time I looked the switch result was communicated back via Wasm locals (set by assignment).

Correct:
```ocaml
  | SwitchE (e, cs) ->
    SR.Vanilla,
    let code1 = compile_exp_vanilla env ae e in
    let (set_i, get_i) = new_local env "switch_in" in
    let (set_j, get_j) = new_local env "switch_out" in

    let rec go env cs = match cs with
      | [] -> CanFail (fun k -> k)
      | {it={pat; exp=e}; _}::cs ->
          let (ae1, code) = compile_pat_local env ae pat in
          orElse ( CannotFail get_i ^^^ code ^^^
                   CannotFail (compile_exp_vanilla env ae1 e) ^^^ CannotFail set_j)
                 (go env cs)
          in
      let code2 = go env cs in
      code1 ^^ set_i ^^ orTrap env code2 ^^ get_j
```

I don’t remember why it was hard to return the result on the stack. Maybe the pattern matching code DSL (`CannotFail` etc.) simply wasn’t set up for it. No need to change that now.

**Comment by crusso** [comment]
Is there any chance of this code going wrong if you are already in the midst of producing a flattened tuple on the stack?

**Comment by nomeata** [comment]
You mean the Switch code or the IF code?

But I don’t think so; whatever is below the stack is untouched by the generated code.

**Comment by crusso** [comment]
> You mean the Switch code or the IF code?
> 
> But I don’t think so; whatever is below the stack is untouched by the generated code.

I meant this PR's code, but I guess these are just extra registers and never live long after a call but always loaded onto the stack

**Comment by crusso** [comment]
> You mean the Switch code or the IF code?
> 
> But I don’t think so; whatever is below the stack is untouched by the generated code.

I meant this PR's code, but I guess these are just extra registers and never live long after a call but always loaded onto the stack

**Comment by nomeata** [comment]
Right, they are always short-lived, from the end of a block or function to directly after the block (or after the call).

**Review by crusso — APPROVED** [review]
Nice one!

**Pull request merged**
